### ISSUE TITLE
git-badges not showing up

### ISSUE THREAD

**Issue by pr2tik1** [puf17640/git-badges#13]
My repo: https://github.com/pr2tik1/pr2tik1 (Visits badge: [![Visits Badge](https://badges.pufler.dev/visits/pr2tik1/pr2tik1)](https://badges.pufler.dev))

Or else anywhere

**Comment by saxobroko** [comment]
The host is currently down.

**Comment by thinkverse** [comment]
Hi, contributor here, I've talked with @puf17640 and he's aware that git-badges is down.
He is away until Thursday but will try to get git-badges up and running again before that.

**Comment by puf17640** [comment]
I am so sorry guys, I am on vacation and I didn't take my macbook with me, I will restart the service tomorrow around 1pm EST

**Comment by pr2tik1** [comment]
That's great! Closing the issue, since you acknowledged it! and yes thanks for such awesome work!

**Comment by puf17640** [comment]
The error was me forgetting to declare a lambda as async, I added a cron schedule that logs the rate limiting stats for my token 👍
