### ISSUE TITLE
Adding minimal style design code in README

### ISSUE THREAD

**Issue by pr2tik1** [puf17640/git-badges#15]
A small idea to add a code in markdown for minimal design, if people people who use git-badges don't know and would like to use it,

[![Visits Badge](https://badges.pufler.dev/visits/puf17640/git-badges)](https://badges.pufler.dev)
to 
[![Visits Badge](https://badges.pufler.dev/visits/puf17640/git-badges?style=for-the-badge)](https://badges.pufler.dev)

code: 
```markdown
[![Visits Badge](https://badges.pufler.dev/visits/puf17640/git-badges?style=for-the-badge)](https://badges.pufler.dev)
```

Adding just:
```markdown
?style=for-the-badge
```

It helped me in my README,
https://github.com/pr2tik1/pr2tik1

(P.S. - Just a suggestion, hope it helps😅)

**Comment by puf17640** [comment]
I mentioned the shields.io styles in the [README](https://github.com/puf17640/git-badges/blob/master/README.md)
