### ISSUE TITLE
Adding last update of the repository

### ISSUE THREAD

**Issue by KarthikNayak024** [puf17640/git-badges#16]
You can add the last update time of any repository.

**Comment by puf17640** [comment]
> You can add the last update time of any repository.

Cool idea! Will do!

**Comment by KarthikNayak024** [comment]
If you can add different styles for the badges it would be great. I think you are using **flat** as the default style. You can add some more styles.

**Comment by puf17640** [comment]
I think I have to make it more clear but it does say that in line 5 of the README 
> All endpoints support the parameters that you can also use for [shields.io](https://shields.io) badges, you can check out the documentation here [shields.io styles](https://shields.io/#styles).

**Comment by KarthikNayak024** [comment]
If I could be of any help please tell. I am ready to contribute to your project.

**Comment by KarthikNayak024** [comment]
> I think I have to make it more clear but it does say that in line 5 of the README
> 
> > All endpoints support the parameters that you can also use for [shields.io](https://shields.io) badges, you can check out the documentation here [shields.io styles](https://shields.io/#styles).

I didn't read it properly. Sorry for that.

**Comment by puf17640** [comment]
Implemented by ac33462
