### ISSUE TITLE
[Idea] badge to tell average contribution rate of the person

### ISSUE THREAD

**Issue by Arsenic-ATG** [puf17640/git-badges#18]
maybe you can create a one which will tell the visitors about average contribution rate of the person.

there are a lot of tools which tells us about total number of contributions that we have done but I have hardly seen any which tells us about average contribution rate.

**Comment by puf17640** [comment]
> maybe you can create a one which will tell the visitors about average contribution rate of the person.
> 
> there are a lot of tools which tells us about total number of contributions that we have done but I have hardly seen any which tells us about average contribution rate.

Do you mean weekly/daily/monthly by 'average' ? I will do my best to find a solution and provide said badge soon! 👍

**Comment by Arsenic-ATG** [comment]
any of them would work.
thanks for looking into it, I would be waiting for it. 🙂

**Comment by puf17640** [comment]
The readme needs to be updated but the badge has been added, check it out!

![](https://badges.pufler.dev/commits/yearly/puf17640)
