### ISSUE TITLE
Visit Badges are not loading

### ISSUE THREAD

**Issue by kermit-klein** [puf17640/git-badges#22]
I realized recently that on my profile and on this repository's readme, visit badges are not loading

![Image](https://i.gyazo.com/2b93ef900a2894146ec64f6eee14904e.png)

**Comment by Ares358** [comment]
Same with me.
Apparently the site's down.
![image](https://user-images.githubusercontent.com/52101053/97532783-107c9900-19dd-11eb-9db4-cd9a964c5441.png)

**Comment by gruvw** [comment]
Same issue regarding "Years on GitHub" badge. The endpoint is not responding.

**Comment by kermit-klein** [comment]
It seems problem has been solved , Can someone else also confirm ?

**Comment by Ares358** [comment]
> 
> 
> It seems problem has been solved , Can someone else also confirm ?

Yep, can confirm it's indeed solved.

**Comment by 0x11DFE** [comment]
> It seems problem has been solved , Can someone else also confirm ?

Got the same issue been waiting few days but doesn't seem to be related to time.
[![Spying Counter](https://badges.pufler.dev/visits/0x11DFE/git-badges?style=for-the-badge&color=e74c3c&logo=github&label=Spying+Counter)](https://github.com/0x11DFE)

```json
{
  "message": "An error occured while processing your request, please create an issue on https://github.com/puf17640/git-badges/issues and give as much detail as you can. Thanks!",
  "error": "Not Found"
}
```
