### ISSUE TITLE
Updated Count

### ISSUE THREAD

**Issue by dhairyaostwal** [puf17640/git-badges#23]
Basically it should indicate how many files have been updated/added in the repo

**Comment by mahendraHegde** [comment]
@dhairyaostwal  do you mean updated/added count wrt the last commit made to that repo?

@puf17640  I'd like to work on it. it that's okay.

**Comment by puf17640** [comment]
> @dhairyaostwal do you mean updated/added count wrt the last commit made to that repo?
> 
> @puf17640 I'd like to work on it. if that's okay.

Sure man! Thanks for asking! 👍
