### ISSUE TITLE
Some badges have died

### ISSUE THREAD

**Issue by on3dd** [puf17640/git-badges#27]
A few days ago, some of the badges suddenly stopped working, including the badges for visitors and contributors, and are still not working 😢

**Comment by WrathChaos** [comment]
All of the badges are dead, I think your server just crash. @puf17640

**Comment by puf17640** [comment]
I did not realise my SSL certs all got invalid on 29th January... I'm going to fix this asap! Sorry guys!

**Comment by JefersonLucas** [comment]
I was going to report this problem, I was thinking I should have put the wrong endpoints, but I saw that there was an error on the server

**Comment by on3dd** [comment]
It looks like the problem has been resolved, thanks!
