### ISSUE TITLE
Commits Count Private Repos

### ISSUE THREAD

**Issue by WrathChaos** [puf17640/git-badges#28]
Hello @puf17640,
Thank you for this project :) 
I think you don't count private repo commit counts but can we also add it with a flag or something? Or does it already included?

Thank you

**Comment by puf17640** [comment]
Hey there @WrathChaos !
Glad you like the project, it's been quite a while so if I am honest, I am not sure if it does include private repos. You can check and implement said flag if you want to, just give me a call and I will assign the issue to you 👍
