### ISSUE TITLE
Commits Badge endpoint not working.

### ISSUE THREAD

**Issue by ClementRoyer** [puf17640/git-badges#30]
Hey,

It look like there is an error with the `Commits Badge` endpoint. It return an `error 500`. 

You can check the error on the official page link : https://pufler.dev/git-badges/ at the `Commits Badge` section.

**Comment by ClementRoyer** [comment]
I found the problem. When github api return 0 commits for the period then it goes to this condition and create an error:

```

**Comment by ClementRoyer** [comment]
I found the problem. When github api return 0 commits for the period then it goes to this condition and create an error:
```
server.js

106 | if (!response.total_count) return createError(res, response.message);

```
 I guess it would be better to change this to 

```
if (response.total_count === undefined) return createError(res, response.message);
```

I will create a PR with this change in a near future

**Comment by puf17640** [comment]
Awesome! Thank you!!!
