### ISSUE TITLE
Issue Commits Badge 

### ISSUE THREAD

**Issue by Code-CHOUDHARY** [puf17640/git-badges#33]
An error occured while processing Commit badage request.
as it was showing error in monthly commit link and yearly and all where working .

[![Commits Badge](https://badges.pufler.dev/commits/monthly/puf17640)](https://badges.pufler.dev/commits/monthly/puf17640)

and also i have correct it please go through my pull request.

**Comment by puf17640** [comment]
There is already a pull request for this issue which I will review shortly! 👍🏻  

Thank you for giving me a notice! 😄
