### ISSUE TITLE
Commit git-badge is broken

### ISSUE THREAD

**Issue by micahmiller18** [puf17640/git-badges#34]
When viewing my personal README.md file my commits image is now a broken image along with the instructions for adding it to the readme file. 

Here is a link to my GitHub where the "commits badge" should be displayed after my repo badge.
https://github.com/mmiller2321

![Screenshot 2021-05-04 235515](https://user-images.githubusercontent.com/83612599/117106173-4015b080-ad34-11eb-8ddc-95a300f7bc8e.png)

**Comment by puf17640** [comment]
Thank you for the notice Micah! I'm currently very busy so I just didn't realise there was an error and not even realised people created issues on here..... shouldn't happen but it did! 😿 

I also saw someone already made a pull request for this issue which I will review shortly after replying to you! 👍🏻
