### ISSUE TITLE
Badges are broken

### ISSUE THREAD

**Issue by atrinh0** [puf17640/git-badges#46]
https://badges.pufler.dev/visits/puf17640/git-badges

Returns a `504`: Gateway time-out error.

<img width="912" alt="Screenshot 2022-03-07 at 13 28 10" src="https://user-images.githubusercontent.com/16542463/157043287-d084f179-322d-401d-9850-feb4d28492c9.png">

**Comment by atrinh0** [comment]
It is working now 👍🏻

**Comment by ExposedCat** [comment]
> It is working now 👍🏻

Is it?

![image](https://user-images.githubusercontent.com/44642024/180639125-e37d30f1-2cd9-4162-817c-fce151358dc4.png)

**Comment by atrinh0** [comment]
@ExposedCat This issue was raised on the 7th March 2022 and promptly fixed the following day.

This exact same issue was raised 16 days ago, https://github.com/puf17640/git-badges/issues/56
And still remains to be an issue.

I have reached out to the @puf17640 to no avail.

**Comment by atrinh0** [comment]
This explains the situation https://github.com/puf17640/git-badges/issues/52#issuecomment-1175265604
