### ISSUE TITLE
Commits Badge

### ISSUE THREAD

**Issue by patarol** [puf17640/git-badges#47]
I've noticed that using 

```
https://badges.pufler.dev/commits/daily/patarol
```

returns

>`{"message":"An error occured while processing your request, please create an issue on https://github.com/puf17640/git-badges/issues and give as much detail as you can. Thanks!"}`

I've also tried to set different periodicity (`monthly`, `yearly`) but still throws same error.

Any clue how to solve this?

**Comment by prabhatsingh014** [comment]
I tried using the monthly and daily commit counts in my profile and it seems to work fine.
Used following code in the profile README

"open angle bracket"img src="https://badges.pufler.dev/commits/daily/prabhatsingh014" /"close angle bracket"

Replace open angle bracket and close angle bracket with < & > respectively.

<img src="https://badges.pufler.dev/commits/daily/prabhatsingh014" />

**Comment by patarol** [comment]
That's odd. I still can't retrieve commits (either `daily` or `monthly`).

**Comment by Achazwl** [comment]
I clone the repo and npm run myself, and it works (But I didn't change the GITHUB_ID and GITHUB_TOKEN in `.env` to mine). And I see the commit badge in README.md is also failed. Does it means the deployment of this repo is not up to date?
