### ISSUE TITLE
Badges not working

### ISSUE THREAD

**Issue by 13atm01** [puf17640/git-badges#52]
https://badges.pufler.dev/visits/13atm01/GRUB-Theme

Error `521` Web server is down

![Screenshot_20220702_015604](https://user-images.githubusercontent.com/75361601/176954463-24d9cc71-6cff-4158-aa25-94aacafafd47.png)

**Comment by SimplyVoid** [comment]
hm same issue🤔

**Comment by puf17640** [comment]
oh yeah, I need to host it on another server soon, currently way to busy to do. if someone has the time, I'd appreciate them hosting it and contacting me at julian@pufler.dev so I can set the DNS records to their server so it will work again

**Comment by nevillionaire** [comment]
Awesome

**Comment by 13atm01** [comment]
Thanks @STRRL ,Awesome, It's Work 

![Screenshot_20220708_233928](https://user-images.githubusercontent.com/75361601/178034743-95b65c67-e729-43d4-b9d0-3f3962c1fb56.png)

**Comment by puf17640** [comment]
@STRRL wow! very nice work man! I'll add it to the README to redirect anyone to your repository 👍🏻
