### ISSUE TITLE
Bages not working because the website is down

### ISSUE THREAD

**Issue by katorly** [puf17640/git-badges#56]
As it's said in the issue title, the website is currently down, making the bages inaccessible.  
Is this a mistake or is the project discontinued? Thanks

**Comment by borjapazr** [comment]
Hi @katorly , do you have plans to get the service back up? Thanks 🙏

**Comment by katorly** [comment]
> Hi @katorly , do you have plans to get the service back up? Thanks 🙏

i have no idea

**Comment by STRRL** [comment]
Hi @katorly, @borjapazr, @puf17640, me again.

I created a similar project which could be an alternative to this project, please give it a try: https://github.com/puf17640/git-badges/issues/52#issuecomment-1175972488

**Comment by pujux** [comment]
So just so you guys know, the API is up and running again and will be doing so for a long time now.
