### ISSUE TITLE
Badges are down?

### ISSUE THREAD

**Issue by dimkagithub** [puf17640/git-badges#62]
Hi!
Some time ago badges stopped showing stats.
How can I fix it?

<img width="494" alt="Снимок экрана 2023-01-15 в 00 30 45" src="https://user-images.githubusercontent.com/71010307/212492824-24569ac2-b440-4c99-b827-d6988b1e789d.png">

**Comment by Slluxx** [comment]
@puf17640

**Comment by katorly** [comment]
> @puf17640

Please use https://github.com/puf17640/git-badges/issues/52#issuecomment-1175972488
The author may have stopped developing the project

**Comment by dimkagithub** [comment]
> @dimkagithub @Slluxx
> 
> Please use [#52 (comment)](https://github.com/puf17640/git-badges/issues/52#issuecomment-1175972488) The author may have stopped developing the project

Thanks. Will try )

**Comment by pujux** [comment]
So just so you guys know, the API is up and running again and will be doing so for a long time now.
